version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5500:5500"
    volumes:
      - .:/code
    command: python run.py
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - worker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis