version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5500:5500"
    volumes:
      - .:/code
    command: python run.py
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/code