leech_abilities = [
    "Holy Shock",
    "Holy Shock (Divine Toll)",
    "Holy Shock (Divine Resonance)",
    "Holy Shock (Rising Sunlight)",
    "Word of Glory",
    "Light of Dawn",
    "Holy Light",
    "Flash of Light",
    "Afterimage",
    "Tyr's Deliverance",
    "Glimmer of Light",
    "Light's Hammer",
    "Holy Prism",
    "Holy Reverberation",
    "Dreaming Devotion",
    "Authority of Fiery Resolve",
    "Dawnlight",
    "Dawnlight (HoT)",
    "Eternal Flame",
    "Eternal Flame (HoT)",
    "Sun's Avatar"
]